import 'dart:io' show File;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import '../providers/language_provider.dart';
import '../models/car.dart';

class AddCarScreen extends StatefulWidget {
  final Car? car; 
  const AddCarScreen({super.key, this.car});

  @override
  State<AddCarScreen> createState() => _AddCarScreenState();
}

class _AddCarScreenState extends State<AddCarScreen> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _brandController;
  late TextEditingController _modelController;
  late TextEditingController _priceController;
  late TextEditingController _descController;
  late TextEditingController _seatsController;
  late TextEditingController _imageUrlController; 
  
  Transmission _transmission = Transmission.automatic;
  FuelType _fuelType = FuelType.petrol;
  CarCategory _category = CarCategory.sedan;
  
  String? _selectedDriverId;
  String? _selectedDriverName;
  Map<String, dynamic>? _selectedDriverData;
  XFile? _pickedFile;
  bool _isLoading = false;
  String? _autoGeneratedUrl;

  @override
  void initState() {
    super.initState();
    _brandController = TextEditingController(text: widget.car?.brand ?? '');
    _modelController = TextEditingController(text: widget.car?.model ?? '');
    _priceController = TextEditingController(text: widget.car?.pricePerDay.toString() ?? '');
    _descController = TextEditingController(text: widget.car?.description ?? '');
    _seatsController = TextEditingController(text: widget.car?.seats.toString() ?? '5');
    _imageUrlController = TextEditingController(text: widget.car?.imageUrl ?? '');
    
    if (widget.car != null) {
      _transmission = widget.car!.transmission;
      _fuelType = widget.car!.fuelType;
      _category = widget.car!.category;
      _selectedDriverId = widget.car!.driverId;
      _selectedDriverName = widget.car!.driverName;
    }

    _brandController.addListener(_updateAutoImage);
    _modelController.addListener(_updateAutoImage);
    _imageUrlController.addListener(() => setState(() {}));
  }

  void _updateAutoImage() {
    if (_brandController.text.isNotEmpty && _modelController.text.isNotEmpty && _imageUrlController.text.isEmpty && _pickedFile == null) {
      setState(() {
        String query = "${_brandController.text.trim()},${_modelController.text.trim()},car";
        _autoGeneratedUrl = "https://loremflickr.com/800/600/$query";
      });
    }
  }

  Future<void> _pickImage() async {
    final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(source: ImageSource.gallery, imageQuality: 40);
    if (image != null) setState(() {
       _pickedFile = image;
       _imageUrlController.clear();
    });
  }

  Future<void> _saveCar() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedDriverId == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Tafadhali mchague dereva!")));
      return;
    }
    
    setState(() => _isLoading = true);

    try {
      String imageUrl = _imageUrlController.text.trim();
      if (_pickedFile != null) {
        String fileName = 'car_${DateTime.now().millisecondsSinceEpoch}.jpg';
        final storageRef = FirebaseStorage.instance.ref().child('car_images').child(fileName);
        if (kIsWeb) { await storageRef.putData(await _pickedFile!.readAsBytes()); } else { await storageRef.putFile(File(_pickedFile!.path)); }
        imageUrl = await storageRef.getDownloadURL();
      } else if (imageUrl.isEmpty) {
        imageUrl = _autoGeneratedUrl ?? 'assets/app_icon.png';
      }

      final carData = {
        'brand': _brandController.text.trim(),
        'model': _modelController.text.trim(),
        'pricePerDay': double.parse(_priceController.text.trim()),
        'imageUrl': imageUrl,
        'description': _descController.text.trim(),
        'seats': int.tryParse(_seatsController.text.trim()) ?? 5,
        'transmission': _transmission.index,
        'fuelType': _fuelType.index,
        'category': _category.index,
        'isAvailable': widget.car?.isAvailable ?? true,
        'status': widget.car?.status ?? 'available',
        'rating': widget.car?.rating ?? 4.5,
        'driverId': _selectedDriverId,
        'driverName': _selectedDriverData?['name'] ?? _selectedDriverName ?? '',
        'driverPhone': _selectedDriverData?['phone'] ?? widget.car?.driverPhone ?? '',
        'driverAge': _selectedDriverData?['age'] ?? widget.car?.driverAge ?? 0,
        'driverImage': _selectedDriverData?['profileImage'] ?? widget.car?.driverImage ?? '',
        'updatedAt': Timestamp.now(),
      };

      String carId;
      if (widget.car == null) {
        carData['createdAt'] = Timestamp.now();
        final docRef = await FirebaseFirestore.instance.collection('cars').add(carData);
        carId = docRef.id;
      } else {
        carId = widget.car!.id;
        await FirebaseFirestore.instance.collection('cars').doc(carId).update(carData);
      }

      await FirebaseFirestore.instance.collection('users').doc(_selectedDriverId).update({
        'assignedCarId': carId,
        'assignedCar': "${_brandController.text.trim()} ${_modelController.text.trim()}",
        'assignedCarImage': imageUrl,
      });

      if (mounted) {
        setState(() => _isLoading = false);
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isLoading = false);
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final lang = Provider.of<LanguageProvider>(context);
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text(widget.car == null ? lang.translate('Add Vehicle', 'Sajili Gari') : lang.translate('Edit Vehicle', 'Hariri Gari'), 
          style: const TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF1D275F))),
        backgroundColor: Colors.white, elevation: 0,
      ),
      body: _isLoading 
          ? const Center(child: CircularProgressIndicator(color: Color(0xFF1D275F)))
          : SingleChildScrollView(
              padding: const EdgeInsets.all(25),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(height: 180, width: double.infinity, decoration: BoxDecoration(color: const Color(0xFFF5F6F9), borderRadius: BorderRadius.circular(20)), child: ClipRRect(borderRadius: BorderRadius.circular(20), child: _buildImagePreview())),
                    const SizedBox(height: 15),
                    _buildTextField(_imageUrlController, lang.translate('Image URL', 'URL ya Picha'), Icons.link),
                    const SizedBox(height: 25),

                    _buildSectionTitle(lang.translate('Basic Info', 'Taarifa za Msingi')),
                    _buildDriverPicker(lang),
                    const SizedBox(height: 15),
                    _buildTextField(_brandController, lang.translate('Brand', 'Chapa'), Icons.directions_car),
                    const SizedBox(height: 15),
                    _buildTextField(_modelController, lang.translate('Model', 'Modeli'), Icons.model_training),
                    const SizedBox(height: 15),
                    _buildTextField(_priceController, lang.translate('Price/Day', 'Bei kwa Siku'), Icons.payments, isNumber: true),
                    
                    const SizedBox(height: 25),
                    _buildSectionTitle(lang.translate('Vehicle Specifications', 'Sifa za Gari')),
                    _buildTextField(_seatsController, lang.translate('Seats', 'Idadi ya Viti'), Icons.event_seat, isNumber: true),
                    const SizedBox(height: 15),
                    
                    Row(
                      children: [
                        Expanded(
                          child: _buildDropdown<Transmission>(
                            label: lang.translate('Gear', 'Gia'),
                            value: _transmission,
                            items: [
                              DropdownMenuItem(value: Transmission.automatic, child: Text(lang.translate('Automatic', 'Auto'))),
                              DropdownMenuItem(value: Transmission.manual, child: Text(lang.translate('Manual', 'Manual'))),
                            ],
                            onChanged: (val) => setState(() => _transmission = val!),
                          ),
                        ),
                        const SizedBox(width: 15),
                        Expanded(
                          child: _buildDropdown<FuelType>(
                            label: lang.translate('Fuel', 'Mafuta'),
                            value: _fuelType,
                            items: [
                              DropdownMenuItem(value: FuelType.petrol, child: Text(lang.translate('Petrol', 'Petrol'))),
                              DropdownMenuItem(value: FuelType.diesel, child: Text(lang.translate('Diesel', 'Diesel'))),
                            ],
                            onChanged: (val) => setState(() => _fuelType = val!),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 15),
                    _buildDropdown<CarCategory>(
                      label: lang.translate('Category', 'Kundi la Gari'),
                      value: _category,
                      items: CarCategory.values.map((c) => DropdownMenuItem(value: c, child: Text(c.name.toUpperCase()))).toList(),
                      onChanged: (val) => setState(() => _category = val!),
                    ),
                    
                    const SizedBox(height: 25),
                    _buildSectionTitle(lang.translate('Description', 'Maelezo ya Ziada')),
                    _buildTextField(_descController, lang.translate('Write details...', 'Andika maelezo hapa...'), Icons.description, maxLines: 3),
                    
                    const SizedBox(height: 40),
                    SizedBox(width: double.infinity, height: 60, child: ElevatedButton(onPressed: _saveCar, style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF1D275F), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15))), child: Text(lang.translate('SAVE VEHICLE', 'HIFADHI GARI'), style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)))),
                  ],
                ),
              ),
            ),
    );
  }

  Widget _buildSectionTitle(String title) => Padding(padding: const EdgeInsets.only(bottom: 10), child: Text(title, style: const TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF1D275F))));

  Widget _buildDriverPicker(LanguageProvider lang) {
    return StreamBuilder<QuerySnapshot>(
      stream: FirebaseFirestore.instance.collection('users').where('role', isEqualTo: 'driver').snapshots(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) return const LinearProgressIndicator();
        final drivers = snapshot.data!.docs;
        return Container(
          padding: const EdgeInsets.symmetric(horizontal: 15), decoration: BoxDecoration(color: const Color(0xFFF5F6F9), borderRadius: BorderRadius.circular(15)),
          child: DropdownButtonHideUnderline(
            child: DropdownButton<String>(
              hint: Text(lang.translate('Select Driver', 'Chagua Dereva')), value: _selectedDriverId, isExpanded: true,
              items: drivers.map((doc) { final d = doc.data() as Map<String, dynamic>; return DropdownMenuItem(value: doc.id, child: Text(d['name'] ?? 'No Name')); }).toList(),
              onChanged: (val) {
                setState(() {
                  _selectedDriverId = val;
                  final doc = drivers.firstWhere((d) => d.id == val);
                  _selectedDriverData = doc.data() as Map<String, dynamic>;
                  _selectedDriverName = _selectedDriverData?['name'];
                });
              },
            ),
          ),
        );
      },
    );
  }

  Widget _buildImagePreview() {
    if (_pickedFile != null) return kIsWeb ? Image.network(_pickedFile!.path, fit: BoxFit.cover) : Image.file(File(_pickedFile!.path), fit: BoxFit.cover);
    if (_imageUrlController.text.isNotEmpty) return Image.network(_imageUrlController.text, fit: BoxFit.cover, errorBuilder: (c,e,s) => const Icon(Icons.broken_image));
    if (_autoGeneratedUrl != null) return Image.network(_autoGeneratedUrl!, fit: BoxFit.cover);
    return const Center(child: Icon(Icons.image, size: 50, color: Colors.grey));
  }

  Widget _buildTextField(TextEditingController controller, String label, IconData icon, {bool isNumber = false, int maxLines = 1}) {
    return TextFormField(
      controller: controller, keyboardType: isNumber ? TextInputType.number : TextInputType.text, maxLines: maxLines,
      decoration: InputDecoration(labelText: label, prefixIcon: Icon(icon, color: const Color(0xFF1D275F)), filled: true, fillColor: const Color(0xFFF5F6F9), border: OutlineInputBorder(borderRadius: BorderRadius.circular(15), borderSide: BorderSide.none)),
      validator: (v) => v!.isEmpty ? 'Lazima' : null,
    );
  }

  Widget _buildDropdown<T>({required String label, required T value, required List<DropdownMenuItem<T>> items, required ValueChanged<T?> onChanged}) {
    return DropdownButtonFormField<T>(
      value: value, items: items, onChanged: onChanged,
      decoration: InputDecoration(labelText: label, filled: true, fillColor: const Color(0xFFF5F6F9), border: OutlineInputBorder(borderRadius: BorderRadius.circular(15), borderSide: BorderSide.none)),
    );
  }
}
